import Container from 'react-bootstrap/Container';
import Alert from 'react-bootstrap/Alert';
import Accordion from 'react-bootstrap/Accordion';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';
import ButtonGroup from 'react-bootstrap/ButtonGroup';
import InputGroup from 'react-bootstrap/InputGroup';
import Form from 'react-bootstrap/Form';
import Modal from 'react-bootstrap/Modal';
import { useEffect, useRef, useState } from 'react';
import { dviDecode } from '@matjp/dvi-decode';
import opentype from 'opentype.js';

const luaFontPath = '/dvi-viewer/lua-font-files';
let firstLoad = true;
let logs = [];

function debugLog(msg){
  logs.push(msg);
}

function WelcomeAlert(props) {
  const [show, setShow] = useState(true);
  if (show) {
    return (
      <Alert show={show} variant="info" dismissible onClose={ () => setShow(false)}>
      <p>
        The file 'align.dvi' was loaded as an example. Download the LaTeX source: <Alert.Link href="./align.tex">align.tex</Alert.Link>
      </p>
      </Alert>
    );
  }
}

function InstructionMessage(props) {
  return(
    <Accordion.Body>    
    <p>
      This is a demo React app for the <code>dvi-decode</code> Javascript module.
      (<a href="https://github.com/matjp/dvi-decode" rel="nofollow">https://github.com/matjp/dvi-decode</a>)
    </p>
    <h4>
      How to produce your own <code>dvi</code> files for display:
    </h4>
    <p>
      DVI Viewer works only with <code>dvi</code> files generated by <code>LuaTeX</code>.
      Use the <code>dvilualatex</code> command to generate the file from your LaTeX source.
    </p>
    <p>
      In order for DVI Viewer to interpret a <code>LuaTeX</code> <code>dvi</code> file 
      correctly it makes some assumptions about the font settings in the <code>LaTeX</code> source file.
    </p>
    <p>
      Please ensure each of the following conditions is met when producing your own <code>dvi</code> file.
    </p>
    <ol>
      <li>Use only OpenType or TrueType fonts. (<b>Note: This demo supports only the Latin Modern font family</b>).</li>
      <li>
        Use the <code>unicode-math</code> package is used if math symbols are used.
      </li>
      <li>
        Explicitly set every font using a <code>fontspec</code> command.
      </li>
      <li>
        <p>Set fonts using filenames rather than proper names i.e.</p>
        <p>
          <code>\setmathfont{'{latinmodern-math.otf}'}[Renderer=OpenType] </code>
        </p>
      </li>
      <li>
        <p>
          Set the option <code>Renderer=Opentype</code> for every font used.
          This ensures the expected character encodings are produced in the <code>dvi</code> file.
        </p>
      </li>
      <li>
        If you are using an AMS Math document class you may need to set the option <code>noamsfonts</code>. i.e.
        <code>\documentclass[noamsfonts]{'{amsart}'}</code>
      </li>
    </ol>
    <div><b>Note that images are not yet supported, just text and rules(lines).</b></div>
    </Accordion.Body>    
  );
}

function SelectFileButton(props) {
  const handleChange = (e) => {
    props.fileEvent(e.target.files[0]);
  };

  return (
    <div className='mt-5' >
      <Form.Label>{props.selectMsg}</Form.Label>
      <Form.Control type="file" accept=".dvi" onChange={handleChange}></Form.Control>
    </div>
  );
}

function DocumentCanvas(props) {
  const cnv = useRef();
  enableHighDPICanvas(cnv.current);
  const ctx = cnv.current ? cnv.current.getContext('2d', { alpha: false }) : undefined;

  useEffect( () => {
    if (ctx) {
      ctx.fillStyle = 'white';
      ctx.fillRect(0, 0, props.widthPixels, props.heightPixels);
      ctx.fillStyle = 'black';
      if (props.doc) {
        const pageIndex = props.pageNo-1;
        props.doc.pages[pageIndex].rules.forEach(
          rule => ctx.fillRect(props.marginPixels + rule.x, rule.y, rule.w, rule.h)
        );
        props.doc.pages[pageIndex].pageFonts.forEach(
          async pageFont => {
            const docFont = props.doc.fonts.find(f => f.fontNum === pageFont.fontNum);
            if (docFont) {
              const otfFont = await opentype.load(docFont.fontPath + docFont.fontName);
              if (otfFont) {
                pageFont.glyphs.forEach(glyph => {
                  let otfGlyph = otfFont.glyphs.get(glyph.glyphIndex);
                  if (otfGlyph)
                    glyph.glyphSizes.forEach(glyphSize =>
                      glyphSize.glyphPlacements.forEach(glyphPlacement => 
                        otfGlyph.draw(ctx, props.marginPixels + glyphPlacement.x, glyphPlacement.y, glyphSize.sz, { features: {hinting: true} })
                      )
                    );
                });
              }
            }
        });
      }
    }
  }, [ctx, props.doc, props.pageNo, props.widthPixels, props.heightPixels, props.marginPixels]);

  return (
    <div
      style={{
        height: props.height ? props.height + "px" : "auto",
        width: props.widthPixels ? props.widthPixels + 10 + "px" : "auto",
        overflowY: 'auto'
      }}
    >
    <canvas ref={cnv} width={props.widthPixels} height={props.heightPixels}></canvas>
    </div>  
  )
}

function enableHighDPICanvas(canvas) {
  if (canvas) {
    var pixelRatio = window.devicePixelRatio || 1;
    if (pixelRatio === 1) return;
    var oldWidth = canvas.width;
    var oldHeight = canvas.height;
    canvas.width = oldWidth * pixelRatio;
    canvas.height = oldHeight * pixelRatio;
    canvas.style.width = oldWidth + 'px';
    canvas.style.height = oldHeight + 'px';
    canvas.getContext('2d', { alpha: false }).scale(pixelRatio, pixelRatio);
  }
}

function LogItem(props) {
  return <div>{props.value}</div>;
}

function ModalLog() {
  const [logShow, setLogShow] = useState(false);

  const handleLogShow = () => setLogShow(true);  
  const handleLogClose = () => setLogShow(false);

  return (
    <>
      <Button variant="primary" onClick={handleLogShow}>
        Show Log
      </Button>    

      <Modal size="lg" backdrop="static" show={logShow} onHide={handleLogClose}>
        <Modal.Header closeButton>
          <Modal.Title>Log Messages</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {logs.map((log, index) => <LogItem key={index} value={log}/>)}
        </Modal.Body>
      </Modal>
    </>
  );
}

function App() { 
  const [debugMode, setDebugMode] = useState(false);
  const [pageWidth, setPageWidth] = useState(8.27); /* in inches (A4 default) */
  const [pageHeight, setPageHeight] = useState(11.69); /* in inches (A4 default) */
  const [dpi, setDpi] = useState(96);
  const [dviData, setDviData] = useState();
  const [mag, setMag] = useState(100);
  const [doc, setDoc] = useState();
  const [pageNo, setPageNo] = useState(0);
  const [pageCount, setPageCount] = useState(0);
  const [widthPixels, setWidthPixels] = useState(() => { return Math.floor(pageWidth * dpi) });
  const [heightPixels, setHeightPixels] = useState(() => { return Math.floor(pageHeight * dpi) });
  const [marginPixels, setMarginPixels] = useState(() => { return Math.floor(dpi) }); /* 1 inch margin @ default 100% mag */
  const [selectMsg, setSelectMsg] = useState('Select a DVI File...');

  const onDebugMode = () => setDebugMode(!debugMode);

  const onFile = (f) => {
    const reader = new FileReader();
    reader.onload = (evt) => {
      setSelectMsg('Select a DVI File...Loading...');
      setDviData(new Uint8Array(evt.target.result));
    }
    reader.readAsArrayBuffer(f);
  }

  const onPageSize = (e) => { 
    const arr = e.target.value.split(':');
    setPageWidth(Number(arr[0]));
    setPageHeight(Number(arr[1]));
    setPageMetrics(mag / 100);
  }

  const onDpi = (e) => { 
    if (e.target.value >= 60 && e.target.value <= 300) {
      setDpi(e.target.value);
      setPageMetrics(mag / 100);
    }
  }

  const onMag = (e) => { 
    if (e.target.value >= 100 && e.target.value <= 200) {
      setMag(e.target.value);
      setPageMetrics(e.target.value / 100);
    }
  }

  function setPageMetrics(scaleFactor) {
    setWidthPixels(Math.floor(pageWidth * dpi * scaleFactor));
    setHeightPixels(Math.floor(pageHeight * dpi * scaleFactor));
    setMarginPixels(Math.floor(dpi * scaleFactor));
  }
  
  useEffect( () => {
    if (firstLoad) {
      firstLoad = false;
      fetch('align.dvi').then(res => res.arrayBuffer())
        .then(ab => setDviData(new Uint8Array(ab)));
    }

    if (dviData)
      fetch('font.map').then(res => res.text())
        .then(text => {
          const fontMap = new Map();        
          const mapLines = text.split('\n');
          mapLines.forEach(line => {
              const words = line.split(':');
              fontMap.set(words[0],words[1]);
          });       
          logs = [];
          dviDecode(dviData, dpi, mag * 10, fontMap, luaFontPath, debugMode, debugLog)
          .then(json => {
            const doc = JSON.parse(json);
            setDoc(doc);
            setPageCount(doc.pages.length);
            setPageNo(1);
            setSelectMsg('Select a DVI File...Loaded.');
          })
          .catch((err) => {
            debugLog(err);
            setSelectMsg('Select a DVI File...Load error. See log for details.');
          });
        })
  }, [dviData, dpi, mag, debugMode] );

  return (
    <Container className=".main_container" fluid>    
      <Row className="top-row">
        <Accordion defaultActiveKey="0">
          <Accordion.Item eventKey="0">
            <Accordion.Header>DVI Viewer for LuaTeX</Accordion.Header>
            <InstructionMessage></InstructionMessage>
          </Accordion.Item>
        </Accordion>
        <WelcomeAlert/>                    
      </Row>
      <Row className="main-row">
        <Col className="side-bar" xxl={2}>
          <ButtonGroup className="bg-side" vertical>
            <InputGroup className="bg-nav">
              <SelectFileButton fileEvent={onFile} selectMsg={selectMsg}></SelectFileButton>{' '}
            </InputGroup>
            <InputGroup>
              <InputGroup.Text id="it-pgsz">Page Size</InputGroup.Text>
              <Form.Select onChange={onPageSize}>
                <option value="8.27:11.69">A4</option>                
                <option value="8.5:11">US Letter</option>                
              </Form.Select>
            </InputGroup>    
            <InputGroup>
              <InputGroup.Text id="it-dpi">Display DPI</InputGroup.Text>
              <Form.Control
                type="number"
                value={dpi}
                min="60"
                max="300"
                step="1"
                onChange={onDpi}
              />
            </InputGroup>
            <InputGroup>
              <InputGroup.Text id="it-mag">Magnification(%)</InputGroup.Text>
              <Form.Control
                type="number"
                value={mag}
                min="100"
                max="200"
                step="10"
                onChange={onMag}
              />
            </InputGroup>               
            <Button>Page {pageNo} of {pageCount}</Button>                     
            <ButtonGroup>
              <Button onClick={() => { if (pageNo > 1) setPageNo(pageNo-1) }}>Prev Page</Button>
              <Button onClick={() => { if (pageNo < pageCount) setPageNo(pageNo+1) }}>Next Page</Button>
            </ButtonGroup> 
          </ButtonGroup>
          <p>&nbsp;</p>
            <ButtonGroup className="me-2">
              <ModalLog/>
            </ButtonGroup>            
            <Form.Group className="me-2">
              <Form.Check type="checkbox" label="Debug mode" checked={debugMode} onChange={onDebugMode}/>
            </Form.Group>
        </Col>
        <Col className="doc">
          <DocumentCanvas
            height={window.innerHeight} doc={doc} pageNo={pageNo} widthPixels={widthPixels} heightPixels={heightPixels} marginPixels={marginPixels}>
          </DocumentCanvas>
        </Col>
      </Row>
    </Container>    
  );
}

export default App;
