import Accordion from 'react-bootstrap/Accordion';

export default function InstructionMessage(props) {
    return(
        <Accordion defaultActiveKey="0">
            <Accordion.Item eventKey="0">
            <Accordion.Header>DVI Viewer for LuaTeX</Accordion.Header>
            <Accordion.Body>    
            <p>
                This is a demo React app for the <code>dvi-decode</code> Javascript module.
                (<a href="https://github.com/matjp/dvi-decode" rel="nofollow">https://github.com/matjp/dvi-decode</a>)
            </p>
            <h4>
                How to produce your own <code>dvi</code> files for display:
            </h4>
            <p>
                DVI Viewer works only with <code>dvi</code> files generated by <code>LuaTeX</code>.
                Use the <code>dvilualatex</code> command to generate the file from your LaTeX source.
            </p>
            <p>
                In order for DVI Viewer to interpret a <code>LuaTeX</code> <code>dvi</code> file 
                correctly it makes some assumptions about the font settings in the <code>LaTeX</code> source file.
            </p>
            <p>
                Please ensure each of the following conditions is met when producing your own <code>dvi</code> file.
            </p>
            <ol>
                <li>Use only OpenType or TrueType fonts. (<b>Note: This demo supports only the Latin Modern font family</b>).</li>
                <li>
                Use the <code>unicode-math</code> package is used if math symbols are used.
                </li>
                <li>
                Explicitly set every font using a <code>fontspec</code> command.
                </li>
                <li>
                <p>Set fonts using filenames rather than proper names i.e.</p>
                <p>
                    <code>\setmathfont{'{latinmodern-math.otf}'}[Renderer=OpenType] </code>
                </p>
                </li>
                <li>
                <p>
                    Set the option <code>Renderer=Opentype</code> for every font used.
                    This ensures the expected character encodings are produced in the <code>dvi</code> file.
                </p>
                </li>
                <li>
                If you are using an AMS Math document class you may need to set the option <code>noamsfonts</code>. i.e.
                <code>\documentclass[noamsfonts]{'{amsart}'}</code>
                </li>
            </ol>
            </Accordion.Body>    
            </Accordion.Item>
        </Accordion>
    );
  }
  